targets:
  - name: staging
    args:
      environment: staging
    # Adding a context to .kluctl.yaml helps prevent accidentally deploying to the wrong cluster!
    context: devops-directive-kubernetes-course

  - name: production
    args:
      environment: production
    # Adding a context to .kluctl.yaml helps prevent accidentally deploying to the wrong cluster!
    context: gke_project-3bded169-ecc6-4e03-a6e_asia-southeast1-b_devops-directive-kubernetes-course

args:
  - name: environment

discriminator: kluctl-{{ target.name }}
